packages:
  - "."

allowBuilds:
  esbuild: true

overrides:
  default-browser: 5.5.0
  electron-to-chromium: 1.5.349
  eventsource-parser: 3.0.6
  recast: 0.23.11
  update-browserslist-db: 1.1.3

confirmModulesPurge: false
engineStrict: false
